version: '3'

services:
    react_ui:
        container_name: react_ui
        build: frontend/.
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - django_api

    django_api:
        container_name: django_api
        build: backend/.
        entrypoint: "backend/docker-entrypoint.sh"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - mysql_db

    mysql_db:
        container_name: mysql_db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysecurepass
            MYSQL_DATABASE: mydb
        ports:
            - '3306:3306'
        volumes:
            - ./database:/var/lib/mysql
