version: '3'

services:
    django_api:
        container_name: django_api
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - mysql_db

    mysql_db:
        container_name: mysql_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysecurepass
            MYSQL_DATABASE: mydb
        ports:
            - '3306:3306'
        volumes:
            - ./database:/var/lib/mysql
