# Generated by Django 3.2.15 on 2022-08-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Enter field documentation', max_length=100)),
                ('number', models.IntegerField(help_text='Enter field documentation')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('birthday', models.DateField(help_text='Enter field documentation')),
                ('cpf', models.CharField(help_text='Enter field documentation', max_length=11)),
                ('rg', models.CharField(help_text='Enter field documentation', max_length=9)),
                ('phone', models.CharField(help_text='Enter field documentation', max_length=11)),
                ('adresses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.address')),
            ],
        ),
    ]
